Repository impact-initiatives-hppu/humind, pull requests merged in 2025-10, with the labels that each got.

#645 test(add_loop_healthcare_needed_cat): cover NA handling w/ exhaustive loop grid
  R/add_loop_healthcare_needed_cat.R
  tests/testthat/test-add_loop_healthcare_needed_cat.R
Labels: enhancement

#653 fix(practices, rights): Handle different column separators
  NEWS.md
Labels: bug

#655 Release version 2025.1.3
  DESCRIPTION
  NEWS.md
  R/add_prot_score_practices.R
  R/add_prot_score_rights.R
  README.Rmd
  README.md
  tests/testthat/test-add_prot_score_practices.R
  tests/testthat/test-add_prot_score_rights.R
Labels: Release
