Repository impact-initiatives-hppu/humind, pull requests merged in 2025-07, with the labels that each got.

#588 Issue581 - remove child separation categories and update comp
  NAMESPACE
  R/add_child_sep_cat.R
  R/add_comp_prot.R
  man/add_child_sep_cat.Rd
  man/add_comp_prot.Rd
  tests/testthat/test-add_child_sep_cat.R
  tests/testthat/test-add_comp_prot.R
Labels: enhancement

#591 Issue 577, 586, 587 - update add_fds_cannot_cat.R
  R/add_fds_cannot_cat.R
  man/add_fds_cannot_cat.Rd
  tests/testthat/test-add_fds_cannot_cat.R
Labels: enhancement

#589 Issue580 - update add_handwashing_facility_cat.R
  .Rbuildignore
  .gitignore
  R/add_handwashing_facility_cat.R
  man/add_handwashing_facility_cat.Rd
  tests/testthat/test-add_handwashing_facility_cat.R
Labels: enhancement

#600 Issue575 - Fix wrong assignment for add_comp_health()
  .gitignore
  R/add_comp_health.R
  man/add_comp_health.Rd
  tests/testthat/test-add_comp_health.R
Labels: enhancement

#603 Issue602
  .Rbuildignore
  R/add_comp_edu.R
  R/add_loop_edu_disrupted_d.R
  man/add_comp_edu.Rd
  man/add_loop_edu_disrupted_d.Rd
  tests/testthat/test-add_comp_edu.R
  tests/testthat/test-add_loop_edu_disrupted_d.R
Labels: enhancement

#608 :rotating_light: (tests and coverage) Correctly initialize the usage of {testthat}
  DESCRIPTION
  tests/testthat.R
Labels: bug

#609 Issue604 C&M | add_expenditure_type_infreq_rank.R
  R/add_expenditure_type_infreq_rank.R
  man/add_expenditure_type_infreq_rank.Rd
  tests/testthat/test-add_expenditure_type_infreq_rank.R
Labels: update

#610 :necktie: (add_expenditure_type_prop_infreq) Update implementation of add_expenditure_type_prop_infreq
  R/add_expenditure_type_prop_infreq.R
  man/add_expenditure_type_prop_infreq.Rd
  tests/testthat/test-add_expenditure_type_prop_infreq.R
Labels: update

#616 Implement Protection Composite Scoring and Dimension-Level Indicators (Issue #612)
  DESCRIPTION
  NAMESPACE
  R/add_comp_prot.R
  R/add_prot_score_movement.R
  R/add_prot_score_practices.R
  R/add_prot_score_rights.R
  R/humind-package.R
  man/add_comp_prot.Rd
  man/add_prot_score_movement.Rd
  man/add_prot_score_practices.Rd
  man/add_prot_score_rights.Rd
  tests/testthat/helper.R
  tests/testthat/test-add_comp_prot.R
  tests/testthat/test-add_prot_score_movement.R
  tests/testthat/test-add_prot_score_practices.R
  tests/testthat/test-add_prot_score_rights.R
Labels: update

#621 620 fix failing unit tests
  R/add_drinking_water_source_cat.R
  R/add_loop_edu_access_d.R
  R/add_loop_edu_barrier_protection_d.R
  R/add_loop_wgq_ss.R
  tests/testthat/test-add_drinking_water_source_cat.R
  tests/testthat/test-add_loop_edu_access_d.R
  tests/testthat/test-add_loop_edu_barrier_protection_d.R
  tests/testthat/test-add_loop_wgq_ss.R
Labels: bug

#629 Pre release Clean up
  DESCRIPTION
  R/add_comp_snfi.R
  R/add_shelter_issue_cat.R
  R/num_cat.R
  man/add_comp_snfi.Rd
  tests/testthat/helper.R
  tests/testthat/test-add_access_to_phone_best.R
  tests/testthat/test-add_age_cat.R
  tests/testthat/test-add_comp_edu.R
  tests/testthat/test-add_comp_foodsec.R
  tests/testthat/test-add_comp_health.R
  tests/testthat/test-add_comp_snfi.R
  tests/testthat/test-add_comp_wash.R
  tests/testthat/test-add_drinking_water_source_cat.R
  tests/testthat/test-add_expenditure_type_freq_rank.R
  tests/testthat/test-add_expenditure_type_prop_freq.R
  tests/testthat/test-add_expenditure_type_prop_infreq.R
  tests/testthat/test-add_expenditure_type_zero_freq.R
  tests/testthat/test-add_expenditure_type_zero_infreq.R
  tests/testthat/test-add_fds_cannot_cat.R
  tests/testthat/test-add_handwashing_facility_cat.R
  tests/testthat/test-add_hoh_final.R
  tests/testthat/test-add_income_source_prop.R
  tests/testthat/test-add_income_source_rank.R
  tests/testthat/test-add_income_source_zero_to_sl.R
  tests/testthat/test-add_loop_age_dummy.R
  tests/testthat/test-add_loop_edu_access_d.R
  tests/testthat/test-add_loop_edu_barrier_protection_d.R
  tests/testthat/test-add_loop_edu_disrupted_d.R
  tests/testthat/test-add_loop_edu_ind_age_corrected.R
  tests/testthat/test-add_loop_healthcare_needed_cat.R
  tests/testthat/test-add_loop_wgq_ss.R
  tests/testthat/test-add_msni.R
  tests/testthat/test-add_occupancy_cat.R
  tests/testthat/test-add_prot_score_practices.R
  tests/testthat/test-add_prot_score_rights.R
  tests/testthat/test-add_quantile_interval.R
  tests/testthat/test-add_received_assistance.R
  tests/testthat/test-add_sanitation_facility_cat.R
  tests/testthat/test-add_shelter_damage_cat.R
  tests/testthat/test-add_shelter_issue_cat.R
  tests/testthat/test-add_shelter_type_cat.R
  tests/testthat/test-count_if_above_zero.R
  tests/testthat/test-impute_value.R
  tests/testthat/test-internals.R
  tests/testthat/test-is_in_need.R
  tests/testthat/test-num_cat.R
  tests/testthat/test-rank_top3_vars.R
  tests/testthat/test-reexport-impactR4PHU.R
  tests/testthat/test-sum_vars.R
  tests/testthat/test-value_to_sl.R
Labels: documentation, enhancement

#631 Fix/v2025.1.1
  .gitignore
  DESCRIPTION
  README.Rmd
  README.md
Labels: documentation, update, Release
